=== maiduyenjune/New-portfolio/src/strings/strings.schema.json
{
  "$ref": "#/definitions/Strings",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "SharedStrings": {
      "additionalProperties": false,
      "type": "object"
    },
    "Strings": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "ContactPage": {
          "additionalProperties": false,
          "properties": {
            "description": {
              "type": "string"
            },
            "followOnSocialMedia": {
              "type": "string"
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description",
            "followOnSocialMedia"
          ],
          "type": "object"
        },
        "HomePage": {
          "additionalProperties": false,
          "properties": {
            "Hero": {
              "additionalProperties": false,
              "properties": {
                "description": {
                  "type": "string"
                },
                "title1": {
                  "type": "string"
                },
                "title2": {
                  "type": "string"
                }
              },
              "required": [
                "title2",
                "title1",
                "description"
              ],
              "type": "object"
            }
          },
          "required": [
            "Hero"
          ],
          "type": "object"
        },
        "MyProjects": {
          "additionalProperties": false,
          "properties": {
            "description": {
              "type": "string"
            },
            "personalWork": {
              "type": "string"
            },
            "title": {
              "type": "string"
            }
          },
          "required": [
            "title",
            "description",
            "personalWork"
          ],
          "type": "object"
        },
        "shared": {
          "$ref": "#/definitions/SharedStrings",
          "description": "Shared (reused in several components)"
        }
      },
      "required": [
        "$schema",
        "shared",
        "HomePage",
        "MyProjects",
        "ContactPage"
      ],
      "type": "object"
    }
  }
}

=== maiduyenjune/New-portfolio/src/strings/stringsEn.json
{
  "$schema": "./strings.schema.json",
  "shared": {},
  "ContactPage": {
    "description": "Feel free to contact me. I'm always eager to connect with fellow developers and potential clients!",
    "followOnSocialMedia": "Follow me on Social Media",
    "title": "Have a project in mind or just want to say hi?"
  },
  "HomePage": {
    "Hero": {
      "title1": "Hi I'm min.",
      "title2": "A Front-end Developer",
      "description": "Hello, my name is Nhung Nguyen. I am a skilled web developer. I thoroughly enjoy turning creative ideas into functional and visually appealing websites."
    }
  },
  "MyProjects": {
    "description": "Personal projects reflect my passion for creativity and technology.",
    "personalWork": "PERSONAL WORK",
    "title": "My Projects"
  }
}

=== maiduyenjune/New-portfolio/src/strings/stringsVi.json
{
  "$schema": "./strings.schema.json",
  "shared": {},
  "ContactPage": {
    "description": "Feel free to contact me. I'm always eager to connect with fellow developers and potential clients!",
    "followOnSocialMedia": "Theo dõi mình trên mạng xã hội",
    "title": "Thông tin liên hệ"
  },
  "HomePage": {
    "Hero": {
      "title1": "Xin chào! Mình là Nhung.",
      "title2": "Một lập trình viên Front-end",
      "description": "Xin chào! Mình là Nhung. Một lập trình viên Front-end. Mình viết code."
    }
  },
  "MyProjects": {
    "description": "",
    "personalWork": "DỰ ÁN CÁ NHÂN",
    "title": "Danh Sách Dự Án"
  }
}
